Add codeowners rule for EigenDA docs
Layr-Labs/eigenlayer-docs pull request #146
Opened 2024-03-27 15:36 UTC by teddyknox

Plan:
We will reset the codeowners file to just a few owners to reduce confusion.

2024-03-27 21:00 UTC, eigensid requested changes

2024-03-27 21:00 UTC, eigensid commented on .github/CODEOWNERS
> +docs/eigenlayer/risk/ @0xkydo
Add Sreeram as a reviewer for "Risk"

2024-03-27 21:00 UTC, eigensid commented on .github/CODEOWNERS
> +docs/eigenda/ @teddyknox @eigensid
Also add @jianoaix as reviewer

2024-03-27 21:00 UTC, eigensid commented on .github/CODEOWNERS
> +docs/eigenlayer/ @bpm333
Add @joan-el and @scotthconner as reviewers

2024-03-27 22:06 UTC, eigensid submitted a review, later dismissed

2024-04-01 18:51 UTC, mooselumph approved these changes

2024-04-01 19:20 UTC, dabit3 approved these changes
LGTM

2024-04-01 19:23 UTC, NimaVaziri approved these changes

2024-04-01 19:35 UTC, joan-el approved these changes

2024-04-01 20:06 UTC, wesfloyd approved these changes
lgtm

2024-04-02 19:16 UTC, merged