minor docs updates
Layr-Labs/eigenlayer-docs pull request #156
Opened 2024-03-30 19:35 UTC by andrewkmin

- Fix broken markdown link (https://docs.eigenlayer.xyz/eigenda/operator-guides/networks/goerli)
- Add additional Holesky faucets

2024-04-01 17:09 UTC, wesfloyd approved these changes
lgtm! Thanks for the suggestions

2024-04-01 17:17 UTC, wesfloyd requested changes
Can you please remove the modification to goerli.md? Asking b/c it clashes with this change: https://github.com/Layr-Labs/eigenlayer-docs/pull/158/files

2024-04-01 17:17 UTC, wesfloyd commented on docs/eigenda/operator-guides/networks/goerli.md
> +EigenDA test operator please follow the [Holesky](./holesky.mdx) testnet guide.
Can you please remove this file modification? Asking b/c it clashes with this change: https://github.com/Layr-Labs/eigenlayer-docs/pull/158/files

2024-04-01 22:38 UTC, dabit3 commented
Thanks @andrewkmin if you can rebase / fix merge conflicts, we'll merge, I believe the other issues are fixed (broken link, sidebar position), so consider removing and just leaving the faucet links!

2024-04-03 05:21 UTC, andrewkmin commented
> Thanks @andrewkmin if you can rebase / fix merge conflicts, we'll merge, I believe the other issues are fixed (broken link, sidebar position), so consider removing and just leaving the faucet links!

updated! thanks 🙏

2024-04-03 15:37 UTC, dabit3 approved these changes

2024-04-03 15:38 UTC, merged