feat: move avs rewards integration to avs guide
Layr-Labs/eigenlayer-docs pull request #285
Opened 2024-07-24 21:10 UTC by ypatil12

2024-07-24 22:50 UTC, NimaVaziri approved these changes

2024-07-25 19:30 UTC, wesfloyd requested changes
one minor formatting suggestion. Ok for you?

2024-07-25 19:30 UTC, wesfloyd commented on docs/eigenlayer/restaking-guides/0-restaking-user-guide/testnet/rewards-claiming/rewards-claiming-overview.md
> +Refer to [avs guide](../../../../avs-guides/rewards.md).
```suggestion
Refer to [AVS Guide: AVS Rewards](../../../../avs-guides/rewards.md).
```

2024-07-26 13:47 UTC, wesfloyd approved these changes
lgtm!

2024-07-26 13:47 UTC, merged