Rewards Claim Data (json) Instructions
Layr-Labs/eigenlayer-docs pull request #313
Opened 2024-08-15 15:26 UTC by wesfloyd

<img width="1239" alt="image" src="https://github.com/user-attachments/assets/1884272c-655d-4512-bf1e-65f798ec2844">

2024-08-15 15:41 UTC, seanmcgary requested changes

2024-08-15 16:12 UTC, wesfloyd commented on docs/eigenlayer/rewards-claiming/rewards-snapshot-data.md
> +Daily rewards snapshot distribution data is available via a public S3 bucket. Users may access this data for their own analytics purposes. Follow these steps in order access the data:
Hi @seanmcgary can you confirm the comment above
>Mainnet is actually weekly?

The docs [here](https://github.com/Layr-Labs/eigenlayer-contracts/blob/dev/docs/core/RewardsCoordinator.md#off-chain-calculation) from @8sunyuan and @ypatil12 indicate:
>The pipeline takes snapshots of core contract state at the SNAPSHOT_CADENCE, currently set to **once per day**.

Should we update both docs to indicate something like the following?
>Rewards snapshot frequency is once per week on Mainnet and daily on Testnet.

2024-08-15 16:13 UTC, wesfloyd commented on docs/eigenlayer/rewards-claiming/rewards-snapshot-data.md
> +`https://eigenlabs-rewards-testnet-holesky.s3.amazonaws.com/testnet/holesky/1723075200/claim-amounts.json`
Good call, thanks. Updating now

2024-08-15 16:15 UTC, wesfloyd commented on docs/eigenlayer/rewards-claiming/rewards-snapshot-data.md
> +Daily rewards snapshot distribution data is available via a public S3 bucket. Users may access this data for their own analytics purposes. Follow these steps in order access the data:
good call - adjusted the language now

2024-08-15 16:15 UTC, wesfloyd commented on docs/eigenlayer/rewards-claiming/rewards-snapshot-data.md
> +  * Note: the current snapshot cadence is once per day ([more detail here](https://github.com/Layr-Labs/eigenlayer-contracts/blob/dev/docs/core/RewardsCoordinator.md#off-chain-calculation)).
thanks, updated accordingly

2024-08-16 14:58 UTC, dabit3 approved these changes

2024-08-16 18:29 UTC, seanmcgary approved these changes

2024-08-16 18:29 UTC, merged