docs change for upgrade
Layr-Labs/eigenlayer-docs pull request #76
Opened 2024-02-05 21:31 UTC by shrimalmadhur

- Docs changes for goerli v2 upgrade
- THis will also be valid for m2 mainnet

2024-02-05 23:54 UTC, wesfloyd submitted a review, later dismissed
lgtm

2024-02-06 05:19 UTC, teddyknox submitted a review, later dismissed

2024-02-06 05:40 UTC, shrimalmadhur commented
I will wait for this to be merged once we are ready for upgrade!

2024-02-08 02:13 UTC, eigensid requested changes

2024-02-08 02:13 UTC, eigensid commented on docs/eigenlayer/operator-guides/operator-installation.md
> +For operator registration in a Goerli environment, you need to set the Delegation manager contract address as follows:
capital M in "Delegation Manager"

2024-02-08 21:58 UTC, eigensid approved these changes

2024-02-08 23:37 UTC, merged